# ==============================
#  Data Collection & Cleaning
# ==============================

# STEP 1: load data set

In [1]:
# importing Libraries
import pandas as pd

In [38]:
#----- 1. Load Dataset ----
df = pd.read_csv('mixed_dataset_6000.csv')

In [4]:
import pandas as pd

# Read only first 5000 rows
#df = pd.read_csv('2019-Nov.csv', nrows=5000)

# Save extracted data
#df.to_csv("retail_data_5000.csv", index=False)

In [19]:
df['category_id'] = df['category_id'].astype(str)

In [15]:
#pd.options.display.float_format = '{:.0f}'.format

In [39]:
df.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-11-01 00:00:00 UTC,view,1003461,2053013555631882752,electronics.smartphone,xiaomi,489,520088904,4d3b30da-a5e4-49df-b1a8-ba5943f1dd33
1,2019-11-01 00:00:00 UTC,view,5000088,2053013566100866048,appliances.sewing_machine,janome,294,530496790,8e5f4f83-366c-4f70-860e-ca7417414283
2,2019-11-01 00:00:01 UTC,view,17302664,2053013553853497600,NaN,creed,28,561587266,755422e7-9040-477b-9bd2-6a6e8fd97387
3,2019-11-01 00:00:01 UTC,view,3601530,2053013563810776064,appliances.kitchen.washer,lg,713,518085591,3bfb58cd-7892-48cc-8020-2f17e6de6e7f
4,2019-11-01 00:00:01 UTC,view,1004775,2053013555631882752,electronics.smartphone,xiaomi,183,558856683,313628f1-68b8-460d-84f6-cec7a8796ef2

In [40]:
df.dtypes

event_time        object
event_type        object
product_id       float64
category_id      float64
category_code     object
brand             object
price            float64
user_id          float64
user_session      object
dtype: object

In [43]:
df.shape

(6000, 9)

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   event_time     5819 non-null   object
 1   event_type     5840 non-null   object
 2   product_id     5800 non-null   float64
 3   category_id    5800 non-null   float64
 4   category_code  3747 non-null   object
 5   brand          4791 non-null   object
 6   price          5800 non-null   float64
 7   user_id        5800 non-null   float64
 8   user_session   5839 non-null   object
dtypes: float64(4), object(5)
memory usage: 422.0+ KB

# STEP 2: Check Shape, Columns, Info

In [46]:
print("Missing Values BEFORE:\n")
print(df.isnull().sum())

Missing Values BEFORE:

event_time        181
event_type        160
product_id        200
category_id       200
category_code    2253
brand            1209
price             200
user_id           200
user_session      161
dtype: int64

In [47]:
#df['user_session'] = df['user_session'].fillna(df['user_session'].mode()[0])
#df['user_session'] = df['user_session'].fillna(df['user_session'].mean())
#df['user_session'] = df['user_session'].fillna('Unknown')
df = df.dropna(subset=['user_session'])

In [7]:
#df = df['category_code'].fillna('Unknown', inplace = True)
df['category_code'] = df['category_code'].fillna('Unknown')

In [8]:
df['brand'] = df['brand'].fillna('Unknown')

In [9]:
df.isnull().sum()

event_time       0
event_type       0
product_id       0
category_id      0
category_code    0
brand            0
price            0
user_id          0
user_session     0
dtype: int64

In [10]:
df.shape

(67501969, 9)

In [11]:
df.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-11-01 00:00:00 UTC,view,1003461,2053013555631882655,electronics.smartphone,xiaomi,489.07,520088904,4d3b30da-a5e4-49df-b1a8-ba5943f1dd33
1,2019-11-01 00:00:00 UTC,view,5000088,2053013566100866035,appliances.sewing_machine,janome,293.65,530496790,8e5f4f83-366c-4f70-860e-ca7417414283
2,2019-11-01 00:00:01 UTC,view,17302664,2053013553853497655,Unknown,creed,28.31,561587266,755422e7-9040-477b-9bd2-6a6e8fd97387
3,2019-11-01 00:00:01 UTC,view,3601530,2053013563810775923,appliances.kitchen.washer,lg,712.87,518085591,3bfb58cd-7892-48cc-8020-2f17e6de6e7f
4,2019-11-01 00:00:01 UTC,view,1004775,2053013555631882655,electronics.smartphone,xiaomi,183.27,558856683,313628f1-68b8-460d-84f6-cec7a8796ef2

In [13]:
df = df[df['category_code'] == 'Unknown']

In [14]:
df

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
2,2019-11-01 00:00:01 UTC,view,17302664,2053013553853497655,Unknown,creed,28.31,561587266,755422e7-9040-477b-9bd2-6a6e8fd97387
7,2019-11-01 00:00:02 UTC,view,15900065,2053013558190408249,Unknown,rondell,30.86,518574284,5e6ef132-4d7c-4730-8c7f-85aa4082588f
8,2019-11-01 00:00:02 UTC,view,12708937,2053013553559896355,Unknown,michelin,72.72,532364121,0a899268-31eb-46de-898d-09b2da950b24
13,2019-11-01 00:00:04 UTC,view,34600011,2060981320581906480,Unknown,Unknown,20.54,512416379,4dfe2c67-e537-4dc2-ae69-0b65263db091
15,2019-11-01 00:00:06 UTC,view,24900193,2053013562183385881,Unknown,Unknown,1.09,512651494,f603c815-f51a-46fe-9404-cb586e35edaf
...,...,...,...,...,...,...,...,...,...
67501963,2019-11-30 23:59:53 UTC,view,31500157,2053013558031024687,Unknown,luminarc,51.45,549777277,1e0bc18b-93c7-430d-80d8-80134094339b
67501964,2019-11-30 23:59:53 UTC,view,12711053,2053013553559896355,Unknown,tunga,30.12,552749164,8da3b70a-13fd-4769-8e7e-3f9c289fe830
67501968,2019-11-30 23:59:54 UTC,view,3300318,2053013555355058573,Unknown,tefal,128.68,523508285,acb4def3-fcc9-4744-bf78-482a11592fc5
67501973,2019-11-30 23:59:57 UTC,view,10502879,2053013553199186187,Unknown,Unknown,29.60,514007176,941ff09f-c5da-49dd-8501-70c950202a4a
67501974,2019-11-30 23:59:58 UTC,view,15700137,2053013559733912211,Unknown,Unknown,277.74,532714000,02b4131c-0112-4231-aafa-ceaa08e77c1b