# Experiment 1  Solutions (Do by student)
## Data Collection & Cleaning for Retail Dataset

---

###  Import & Load Data

In [17]:
import pandas as pd
import numpy as np

df = pd.read_csv('retail_data.csv')

df.head()

,event_time,event type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-11-01 00:06:51 UTC,view,1001588.0,2.050000e+18,electronics.smartphone,meizu,127.87,528269305.0,6dce75d2-e455-4e52-ab65-af16e36f64cb
1,2019-11-01 00:08:03 UTC,view,1002101.0,2.050000e+18,electronics.smartphone,samsung,370.64,540508491.0,33a0d8f4-c388-4ce7-85f4-7b1f11563d6a
2,2019-11-01 00:16:56 UTC,view,1002101.0,NaN,electronics.smartphone,samsung,370.64,NaN,8f65dac1-e176-4b72-b783-d9c5615ae858
3,2019-11-01 00:19:17 UTC,view,1002101.0,2.050000e+18,electronics.smartphone,samsung,370.64,565859861.0,e280986e-033c-4394-a0df-73354b42b80c
4,2019-11-01 00:27:56 UTC,view,1002101.0,2.050000e+18,electronics.smartphone,samsung,370.64,515031178.0,2cfd4fc1-3201-4c91-86ad-5d79a737c14d

#  Understanding the Data

In [18]:
# a  
df.dtypes

event_time        object
event type        object
product_id       float64
category_id      float64
category_code     object
brand             object
price            float64
user_id          float64
user_session      object
dtype: object

In [19]:
#b
df['event type'].value_counts()

event type
view        4899
purchase      54
cart          52
Name: count, dtype: int64

In [20]:
#c
df['product_id'].value_counts().head(10)

product_id
1004856.0     53
1005115.0     40
1004767.0     39
16000004.0    36
1005105.0     35
1801881.0     34
4804056.0     31
10301494.0    28
1004870.0     27
4804295.0     27
Name: count, dtype: int64

In [21]:
#d
df['price'].describe()

count    5000.000000
mean      295.086700
std       363.228872
min       -50.450000
25%        62.810000
50%       165.260000
75%       373.520000
max      2574.070000
Name: price, dtype: float64

In [22]:
#e
df['brand'].value_counts().head(10)

brand
samsung    517
apple      389
xiaomi     377
huawei      89
lucente     70
sv          69
sony        68
respect     61
rondell     60
bosch       55
Name: count, dtype: int64

In [23]:
#f
df['user_id'].nunique()

1113


# Data Quality & Cleaning

 ## Missing Values

$$
\text{Missing Values} = \sum_{i=1}^{n} I(x_i = \text{NULL}),
\quad
I(x_i) =
\begin{cases}
1, & \text{if } x_i \text{ is NULL} \\
0, & \text{if } x_i \text{ is not NULL}
\end{cases}
$$

In [24]:
#a
df.isnull().sum()

event_time          0
event type          0
product_id         20
category_id         9
category_code    1854
brand             917
price               5
user_id            12
user_session        4
dtype: int64

###  Invalid Values
$$
price \leq 0
$$

In [25]:
#b
df[df['price'] <= 0]

,event_time,event type,product_id,category_id,category_code,brand,price,user_id,user_session
4643,2019-11-01 00:25:52 UTC,view,32401217.0,2.050000e+18,NaN,NaN,-27.03,512483076.0,5e3606fe-e6ba-457e-973c-d56822d9584e
4818,2019-11-01 00:00:35 UTC,view,44300009.0,2.100000e+18,apparel.jeans,NaN,-50.45,545220871.0,f278cca0-e0f6-49a3-819a-d961998282d5

###  Duplicate Records

$$
\text{Duplicates} = \text{Repeated rows}
$$

In [26]:
#c
df.duplicated().sum()

np.int64(5)

### Consistency Check

$$
event\_type \in \{view, cart, purchase\}
$$

In [27]:
#d
df['event type'].unique()
# Yes

array(['view', 'purchase', 'cart'], dtype=object)

###  Completeness

$$
\text{Completeness} = \frac{\text{Non-missing}}{\text{Total}} \times 100
$$

In [30]:
#e
total_cells = df.size
missing_cells = df.isnull().sum().sum()
((total_cells - missing_cells) / total_cells) * 100

np.float64(93.73737373737374)

### Accuracy

$$
\text{Accuracy} = \frac{\text{correct records}}{\text{Total records}} \times 100
$$

In [31]:
#f
valid = df[df['price'] > 0]
(len(valid) / len(df)) * 100

99.86013986013987

###  Consistency

$$
\text{Consistency} = \frac{\text{Consistent records}}{\text{Total records}} \times 100
$$

In [35]:
#g
valid_events = ['view','cart','purchase']
consistent = df[df['event type'].isin(valid_events)]
(len(consistent) / len(df)) * 100

100.0