In [1]:
list1 = [20,30,40,50]

In [2]:
list1

[20, 30, 40, 50]

In [3]:
list1.append(10)

In [4]:
list1

[20, 30, 40, 50, 10]

In [5]:
list1.remove(40)

In [6]:
list1

[20, 30, 50, 10]

In [7]:
list2 = [ "Ram",70 , "A"]

In [8]:
list2

['Ram', 70, 'A']

In [9]:
data = { 
    "id" : 101,
    "name" : "KL",
    "marks": 80
}

In [10]:
data

{'id': 101, 'name': 'KL', 'marks': 80}

In [11]:
import pandas  as pd

In [12]:
df = pd.read_csv("synthetic_retail_dataset.csv")

In [15]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,Date
0,1046,NaN,Monitor,NaN,475.08,104.0,India,2023-01-28 02:00:00
1,1868,A101,Mouse,0.0,905.72,104.0,USA,2023-02-10 08:00:00
2,1452,C303,Mouse,-2.0,115.19,104.0,usa,2023-01-19 23:00:00
3,1098,A101,Monitor,19.0,850.17,101.0,USA,2023-02-01 12:00:00
4,1619,C303,Mouse,7.0,3.01,NaN,UK,2023-01-25 01:00:00

In [16]:
df.tail()

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,Date
1045,1456,A101,Mouse,44.0,662.84,101.0,UK,2023-02-01 07:00:00
1046,1317,B202,NaN,5.0,927.14,104.0,NaN,2023-01-11 12:00:00
1047,1515,B202,NaN,46.0,407.09,102.0,UK,2023-01-20 03:00:00
1048,1444,B202,Mouse,30.0,178.09,NaN,USA,2023-02-06 09:00:00
1049,1279,B202,NaN,14.0,511.01,103.0,usa,2023-01-20 20:00:00

In [17]:
df.shape

(1050, 8)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1050 entries, 0 to 1049
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    1050 non-null   int64
 1   StockCode    832 non-null    object
 2   Description  875 non-null    object
 3   Quantity     1016 non-null   float64
 4   UnitPrice    1000 non-null   float64
 5   CustomerID   838 non-null    float64
 6   Country      879 non-null    object
 7   Date         1050 non-null   object
dtypes: float64(3), int64(1), object(4)
memory usage: 65.8+ KB