# =====================================================
# Python Basics                       
# Author: Nagesh  , Assistant Professor, KL University Hyderabad
# Objective: Learn Python fundamentals for Data Science - Part 1
# =====================================================

In [1]:
print(" This is KL University")

 This is KL University

In [2]:
a = 7

In [3]:
b = 10

In [4]:
print(a+b)

17

In [5]:
a+b

17

In [6]:
z = a+b

In [12]:
print("sum of a and b",z)

sum of a and b 17

In [ ]:
##

In [14]:
 print(" this is text")

 this is text

In [15]:
for i in range(5):
    print(i)

0
1
2
3
4

In [16]:
for i in range(2,21):
    print(i)

2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20

In [17]:
for i in range(2,21,2):
    print(i)

2
4
6
8
10
12
14
16
18
20

In [5]:
x = 30

In [6]:
y = 2.1

In [7]:
z =" This is mdsa"

In [9]:
type(x)

int

In [10]:
type(y)

float

In [11]:
type(z)

str

In [12]:
f = True

In [13]:
type(f)

bool

In [16]:
num = 7
if num > 10 :
    print("given number is greater than 10")
else:
    print("given number lessthan or equal to 10")

given number lessthan or equal to 10

In [17]:
list1 = [ 10,20,30,40]

In [18]:
list1

[10, 20, 30, 40]

In [19]:
list1.append(50)

In [20]:
list1

[10, 20, 30, 40, 50]

In [21]:
list1.remove(30)

In [22]:
list1

[10, 20, 40, 50]

In [23]:
data = {
    "id" : 101,
    "name": "KL",
    "Marks": 70
}

In [24]:
data

{'id': 101, 'name': 'KL', 'Marks': 70}

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("synthetic_retail_dataset.csv")

In [4]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,Date
0,1046,NaN,Monitor,NaN,475.08,104.0,India,2023-01-28 02:00:00
1,1868,A101,Mouse,0.0,905.72,104.0,USA,2023-02-10 08:00:00
2,1452,C303,Mouse,-2.0,115.19,104.0,usa,2023-01-19 23:00:00
3,1098,A101,Monitor,19.0,850.17,101.0,USA,2023-02-01 12:00:00
4,1619,C303,Mouse,7.0,3.01,NaN,UK,2023-01-25 01:00:00

In [5]:
df.tail()

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,Date
1045,1456,A101,Mouse,44.0,662.84,101.0,UK,2023-02-01 07:00:00
1046,1317,B202,NaN,5.0,927.14,104.0,NaN,2023-01-11 12:00:00
1047,1515,B202,NaN,46.0,407.09,102.0,UK,2023-01-20 03:00:00
1048,1444,B202,Mouse,30.0,178.09,NaN,USA,2023-02-06 09:00:00
1049,1279,B202,NaN,14.0,511.01,103.0,usa,2023-01-20 20:00:00

In [6]:
df.shape

(1050, 8)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1050 entries, 0 to 1049
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    1050 non-null   int64
 1   StockCode    832 non-null    object
 2   Description  875 non-null    object
 3   Quantity     1016 non-null   float64
 4   UnitPrice    1000 non-null   float64
 5   CustomerID   838 non-null    float64
 6   Country      879 non-null    object
 7   Date         1050 non-null   object
dtypes: float64(3), int64(1), object(4)
memory usage: 65.8+ KB

In [9]:
data = {
    "id": [100,310,210,300],
    "name": ["john","Ram","neha","shilpa"],
    "marks" : [60,70,80,90]
}

In [11]:
df = pd.DataFrame(data)

In [17]:
df # structured data

    id    name  marks
0  100    john     60
1  310     Ram     70
2  210    neha     80
3  300  shilpa     90

In [13]:
data           # semi stuctured

{'id': [100, 310, 210, 300],
 'name': ['john', 'Ram', 'neha', 'shilpa'],
 'marks': [60, 70, 80, 90]}

In [18]:
text = " This is section 2 class"   # unstuctured data
print(text)

 This is section 2 class