# =====================================================
# Python Basics                       
# Author: Nagesh  , Assistant Professor, KL University Hyderabad
# Objective: Learn Python fundamentals for Data Science - Part 1
# =====================================================

In [1]:
print("This is KL University")

This is KL University

In [2]:
x = 10

In [3]:
y = 20

In [4]:
x+y

30

In [5]:
a = x + y

In [11]:
print("sum of x and y is",a)

sum of x and y is 30

In [12]:
for  i in range(5):
    print(i)

0
1
2
3
4

In [ ]:
##

In [13]:
for i in  range(1,5):
    print(i)

1
2
3
4

In [14]:
for i in range(2,21,2):
    print(i)

2
4
6
8
10
12
14
16
18
20

In [15]:
num = 8
if num > 10 :
    print("number is greater than 10")
else:
    print("number is less than or equal to 10")

number is less than or equal to 10

In [16]:
# creating list

In [17]:
list1 = [20,30,40,50]

In [18]:
list1

[20, 30, 40, 50]

In [19]:
list1.append(60)

In [20]:
list1

[20, 30, 40, 50, 60]

In [21]:
list1.remove(40)

In [22]:
list1

[20, 30, 50, 60]

In [25]:
list2 = [20,"KL",20.1]

In [26]:
list2

[20, 'KL', 20.1]

In [27]:
# Creating Dictionary

In [28]:
data ={
    "id":101,
    "name": "KL",
    "marks": 90
}

In [29]:
data

{'id': 101, 'name': 'KL', 'marks': 90}

## Importing data set

In [1]:
import pandas as pd

In [3]:
df =  pd.read_csv("retail_data.csv")

In [15]:
df.columns

Index(['event_time', 'event type', 'product_id', 'category_id',
       'category_code', 'brand', 'price', 'user_id', 'user_session'],
      dtype='object')

In [7]:
df.head(10)

,event_time,event type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-11-01 00:06:51 UTC,view,1001588.0,2.050000e+18,electronics.smartphone,meizu,127.87,528269305.0,6dce75d2-e455-4e52-ab65-af16e36f64cb
1,2019-11-01 00:08:03 UTC,view,1002101.0,2.050000e+18,electronics.smartphone,samsung,370.64,540508491.0,33a0d8f4-c388-4ce7-85f4-7b1f11563d6a
2,2019-11-01 00:16:56 UTC,view,1002101.0,NaN,electronics.smartphone,samsung,370.64,NaN,8f65dac1-e176-4b72-b783-d9c5615ae858
3,2019-11-01 00:19:17 UTC,view,1002101.0,2.050000e+18,electronics.smartphone,samsung,370.64,565859861.0,e280986e-033c-4394-a0df-73354b42b80c
4,2019-11-01 00:27:56 UTC,view,1002101.0,2.050000e+18,electronics.smartphone,samsung,370.64,515031178.0,2cfd4fc1-3201-4c91-86ad-5d79a737c14d
5,2019-11-01 00:22:25 UTC,view,1002482.0,2.050000e+18,electronics.smartphone,meizu,127.87,534887905.0,6a699abb-bdf8-43b7-86b7-bb89f6e8d4ed
6,2019-11-01 00:24:01 UTC,view,1002482.0,NaN,electronics.smartphone,meizu,127.87,534887905.0,6a699abb-bdf8-43b7-86b7-bb89f6e8d4ed
7,2019-11-01 00:02:18 UTC,view,1002524.0,2.050000e+18,electronics.smartphone,apple,531.26,549256216.0,dcbdc6e4-cd49-4ee8-95c5-e85f3c618fa1
8,2019-11-01 00:02:56 UTC,view,NaN,2.050000e+18,electronics.smartphone,apple,531.26,549256216.0,dcbdc6e4-cd49-4ee8-95c5-e85f3c618fa1
9,2019-11-01 00:08:01 UTC,view,1002524.0,2.050000e+18,NaN,apple,531.26,549256216.0,dcbdc6e4-cd49-4ee8-95c5-e85f3c618fa1

In [8]:
df.tail()

,event_time,event type,product_id,category_id,category_code,brand,price,user_id,user_session
5000,2019-11-01 00:23:46 UTC,view,60500001.0,2.160000e+18,construction.tools.welding,resanta,25.20,520543848.0,936d231c-0f79-4a43-9c22-430667aeb902
5001,2019-11-01 00:23:51 UTC,view,60500001.0,2.160000e+18,construction.tools.welding,resanta,25.20,520543848.0,936d231c-0f79-4a43-9c22-430667aeb902
5002,2019-11-01 00:21:48 UTC,view,60500002.0,2.160000e+18,construction.tools.welding,resanta,42.19,520543848.0,936d231c-0f79-4a43-9c22-430667aeb902
5003,2019-11-01 00:23:27 UTC,view,60500002.0,2.160000e+18,construction.tools.welding,resanta,42.19,520543848.0,936d231c-0f79-4a43-9c22-430667aeb902
5004,2019-11-01 00:24:34 UTC,view,60500002.0,2.160000e+18,construction.tools.welding,resanta,42.19,520543848.0,936d231c-0f79-4a43-9c22-430667aeb902

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5005 entries, 0 to 5004
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   event_time     5005 non-null   object
 1   event type     5005 non-null   object
 2   product_id     4985 non-null   float64
 3   category_id    4996 non-null   float64
 4   category_code  3151 non-null   object
 5   brand          4088 non-null   object
 6   price          5000 non-null   float64
 7   user_id        4993 non-null   float64
 8   user_session   5001 non-null   object
dtypes: float64(4), object(5)
memory usage: 352.0+ KB

In [13]:
df.dtypes

event_time        object
event type        object
product_id       float64
category_id      float64
category_code     object
brand             object
price            float64
user_id          float64
user_session      object
dtype: object

In [14]:
df.shape

(5005, 9)

In [16]:
df.isnull().sum()

event_time          0
event type          0
product_id         20
category_id         9
category_code    1854
brand             917
price               5
user_id            12
user_session        4
dtype: int64

In [19]:
print(df.isnull().sum().sum())

2821