In [1]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [2]:
# Dataset info
df.info()

# Check missing values
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [3]:
# Fill Age with median
df['Age'] = df['Age'].fillna(df['Age'].median())

# Fill Embarked with mode
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

# Drop Cabin (too many missing values)
df = df.drop(columns=['Cabin'])

# Check again
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [4]:
df['Age_Group'] = pd.cut(df['Age'],
                        bins=[0, 18, 35, 60, 100],
                        labels=['Child', 'Young', 'Adult', 'Senior'])

In [5]:
df['Family_Size'] = df['SibSp'] + df['Parch'] + 1

In [6]:
df['Title'] = df['Name'].str.extract(' ([A-Za-z]+)\.', expand=False)

In [7]:
import numpy as np

In [8]:
df['Fare_Log'] = np.log1p(df['Fare'])

In [9]:
# Min-Max Normalization
df['Age_Norm'] = (df['Age'] - df['Age'].min()) / (df['Age'].max() - df['Age'].min())

df['Fare_Norm'] = (df['Fare'] - df['Fare'].min()) / (df['Fare'].max() - df['Fare'].min())

In [10]:
df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})

In [11]:
pd.set_option('display.max_columns', None)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Age_Group,Family_Size,Title,Fare_Log,Age_Norm,Fare_Norm
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,S,Young,2,Mr,2.110213,0.271174,0.014151
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,C,Adult,2,Mrs,4.280593,0.472229,0.139136
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,S,Young,1,Miss,2.188856,0.321438,0.015469
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,S,Young,2,Mrs,3.990834,0.434531,0.103644
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,S,Young,1,Mr,2.202765,0.434531,0.015713

In [12]:
#df = pd.get_dummies(df, columns=['Embarked', 'Age_Group', 'Title'], drop_first=True)
df = pd.get_dummies(df, columns=['Embarked', 'Age_Group', 'Title'], drop_first=True, dtype=int)

In [ ]:
df.columns

In [13]:
df = df.drop(columns=['Name', 'Ticket'])

In [14]:
df.head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Family_Size,Fare_Log,Age_Norm,Fare_Norm,Embarked_Q,Embarked_S,Age_Group_Young,Age_Group_Adult,Age_Group_Senior,Title_Col,Title_Countess,Title_Don,Title_Dr,Title_Jonkheer,Title_Lady,Title_Major,Title_Master,Title_Miss,Title_Mlle,Title_Mme,Title_Mr,Title_Mrs,Title_Ms,Title_Rev,Title_Sir
0,1,0,3,0,22.0,1,0,7.2500,2,2.110213,0.271174,0.014151,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
1,2,1,1,1,38.0,1,0,71.2833,2,4.280593,0.472229,0.139136,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
2,3,1,3,1,26.0,0,0,7.9250,1,2.188856,0.321438,0.015469,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
3,4,1,1,1,35.0,1,0,53.1000,2,3.990834,0.434531,0.103644,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
4,5,0,3,0,35.0,0,0,8.0500,1,2.202765,0.434531,0.015713,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0

In [15]:
df.to_csv("processed_titanic.csv", index=False)